CREATE TABLE zomato(
    state VARCHAR(50),
    city VARCHAR(50),
    order_date varchar(50),
    restaurant_name VARCHAR(150),
    location VARCHAR(100),
    category VARCHAR(500),
    dish_name VARCHAR(1000),
    price_inr NUMERIC(10,2),
    rating NUMERIC(3,1),
    rating_count INT
);


-- convert order_date to date time format.

-- CREATE NEW COLUMN
ALTER TABLE ZOMATO 
ADD COLUMN CLEAN_DATE DATE

-- UPDATE WITH DATES
UPDATE ZOMATO
SET CLEAN_DATE = 
CASE 
WHEN ORDER_DATE IS NULL OR ORDER_DATE = '' THEN NULL
WHEN ORDER_DATE LIKE '%-%' THEN TO_DATE(ORDER_DATE,'DD-MM-YYYY')
WHEN ORDER_DATE LIKE '%/%' THEN TO_DATE(ORDER_DATE,'MM/DD/YYYY')
END

-- DELETE OLD COLUMN
ALTER TABLE ZOMATO
DROP COLUMN ORDER_DATE

-- RENAME THE NEW COLUMN
ALTER TABLE ZOMATO
RENAME COLUMN CLEAN_DATE TO ORDER_DATE

-- RENAME PRICE COLUMN
ALTER TABLE ZOMATO
RENAME COLUMN PRICE_INR TO PRICE


-- ORDER ALL NAMES
UPDATE ZOMATO 
SET LOCATION = TRIM(INITCAP(LOWER(LOCATION)))

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


                                                         


-- 1. TOTAL / AVERAGE REVENURE

SELECT SUM(PRICE) FROM ZOMATO

SELECT ROUND(AVG(PRICE),2) FROM ZOMATO

--2. STATE,CITY WISE REVENUE TOP 10 

SELECT STATE,CITY,SUM(PRICE) AS TOTAL_REVENUE, ROUND(AVG(PRICE),2) AS AVERAGE_REVENUE FROM ZOMATO GROUP BY 1,2 ORDER BY 3 DESC,4 DESC LIMIT 10

-- 3. MONTHLY REVENUE , TOP 3 SPENDING STATES IN EACH MONTH

WITH MONTH_SPEND AS (
SELECT STATE,CITY, EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,SUM(PRICE) AS TOTAL_REVENUE FROM ZOMATO GROUP BY 1,2,3 ),

MONTHLY_RANKING AS (
SELECT *,ROW_NUMBER() OVER(PARTITION BY MONTH ORDER BY TOTAL_REVENUE DESC) AS RK FROM MONTH_SPEND)

SELECT TO_CHAR(TO_DATE(MONTH::TEXT,'MM'),'MON') AS MONTH,
STATE,CITY,TOTAL_REVENUE FROM MONTHLY_RANKING WHERE RK IN (1,2,3)

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                                                       -- FOOD RELATED ANALYSIS


-- FEATURE ENGINEERING

ALTER TABLE zomato
ADD COLUMN BAKERY_ITEMS INT,
ADD COLUMN SWEETS INT,
ADD COLUMN BEVERAGES INT,
ADD COLUMN NON_VEG INT,
ADD COLUMN FAST_FOOD INT,
ADD COLUMN VEG_MEALS INT,
ADD COLUMN INTERNATIONAL_CUISINE INT,
ADD COLUMN TIFFINS INT

-- UPDATE VALUES

UPDATE zomato
SET

-- BAKERY ITEMS
BAKERY_ITEMS = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%CAKE%','%PASTRY%','%BROWNIE%','%JAR%','%SLICES%','%HAMPERS%','%BREADS%','%COOKIES%'])
    THEN 1 ELSE 0 END,

-- SWEETS
SWEETS = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%DESSERTS%','%SWEETS%','%LADDU SPECIAL%'])
    THEN 1 ELSE 0 END,

-- BEVERAGES 
BEVERAGES = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%ICE CREAM%','%JUICE%','%DRINK%','%BEVERAGES%','%SHAKES%','%COFFEE%','%TEA%','%SODA%'])
         AND CATEGORY NOT ILIKE '%ICE CREAM CAKES%'
    THEN 1 ELSE 0 END,

-- NON VEG 
NON_VEG = CASE 
    WHEN DISH_NAME ILIKE ANY(ARRAY['%CHICKEN%','%MUTTON%','%EGG%','%FISH%','%PRAWN%','%CRAB%','%BEEF%'])
    THEN 1 ELSE 0 END,

-- FAST FOOD
FAST_FOOD = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%PIZZA%','%SANDWICH%','%FAST FOOD%','%VADA PAV%','%PASTA%','%BURGER%','%NOODLES%','%MAGGI%','%ROLL%','%WRAPS%','%TACOS%','%FRENCH FRIES%'])
    THEN 1 ELSE 0 END,

-- VEG MEALS
VEG_MEALS = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%RICE%','%SABJI%','%PAPAD%','%SALAD%','%DAL%','%MEALS%','%POHA%','%PANEER%','%MUSHROOM%'])
    THEN 1 ELSE 0 END,

-- INTERNATIONAL CUISINE
INTERNATIONAL_CUISINE = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%CHINESE%','%RAMEN%','%KOREAN%','%THAI%','%ARABIC%','%ARABIAN%'])
    THEN 1 ELSE 0 END,

-- TIFFINS
TIFFINS = CASE 
    WHEN CATEGORY ILIKE ANY(ARRAY['%DOSA%','%IDLY%','%RAVA DOSA%','%PAROTTA%','%UTTHAPAM%','%BREAK FAST%','%SOUTH INDIAN%','%BONDA%'])
    THEN 1 ELSE 0 END;



-- REVENUE ANALYSIS


-- BAKERY ITEMS
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE BAKERY_ITEMS = 1 GROUP BY 1,2 ORDER BY 4 DESC

--  SWEETS  
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE SWEETS = 1 GROUP BY 1,2 ORDER BY 4 DESC

--  BEVERAGES
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE BEVERAGES = 1 GROUP BY 1,2 ORDER BY 4 DESC


-- NON VEG
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE NON_VEG = 1 GROUP BY 1,2 ORDER BY 4 DESC


-- FAST FOOD
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE FAST_FOOD = 1 GROUP BY 1,2 ORDER BY 4 DESC


-- VEG MEALS
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE VEG_MEALS = 1 GROUP BY 1,2 ORDER BY 4 DESC


-- INTERNATIONAL_CUISINE
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE INTERNATIONAL_CUISINE = 1 GROUP BY 1,2 ORDER BY 4 DESC


-- TIFFINS
SELECT STATE,CITY,COUNT(*) AS NO_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO WHERE TIFFINS = 1 GROUP BY 1,2 ORDER BY 4 DESC

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                                                    -- RESTAURANT ANALYSIS
													-------------------------
													
--  5. top 3  restaurants  WITH MOST ORDERS in each city

WITH AVERAGE_RATING AS(
select STATE,CITY,RESTAURANT_NAME,ROUND(AVG(RATING),2) AS RATING,COUNT(*) AS FREQUENCY FROM ZOMATO GROUP BY 1,2,3 ),

RANKING AS(
SELECT *,ROW_NUMBER() OVER(PARTITION BY STATE ORDER BY FREQUENCY DESC,RATING DESC) AS RK FROM AVERAGE_RATING)

SELECT STATE,CITY,RESTAURANT_NAME,RATING,FREQUENCY FROM RANKING WHERE RK IN (1,2,3)


--  6. TOP 3 RESTAURANTS WITH TOP RATINGS IN EACH CITY

WITH AVERAGE_RATING AS(
select STATE,CITY,RESTAURANT_NAME,ROUND(AVG(RATING),2) AS RATING,COUNT(*) AS FREQUENCY FROM ZOMATO GROUP BY 1,2,3 ),

RANKING AS(
SELECT *,ROW_NUMBER() OVER(PARTITION BY STATE ORDER BY RATING DESC,FREQUENCY DESC) AS RK FROM AVERAGE_RATING)

SELECT STATE,CITY,RESTAURANT_NAME,RATING,FREQUENCY FROM RANKING WHERE RK IN (1,2,3)

-- 7. RESTAURANT POTENTIONAL FOR ZOMATO IN EACH CITY

SELECT STATE,CITY,COUNT(DISTINCT RESTAURANT_NAME) AS COUNT_OF_LOCATION FROM ZOMATO GROUP BY 1,2 ORDER BY 3 DESC

SELECT * FROM ZOMATO
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                                                  -- LOCATIONS IN EACH CITY
												  --------------------------

--  8. ZOMATO SPREAD IN DIFFERENT CITIES

SELECT STATE,CITY,COUNT(DISTINCT LOCATION) AS COUNT_OF_LOCATION FROM ZOMATO GROUP BY 1,2 ORDER BY 3 DESC

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

												 -- TIME BASED ANALYSIS
												 -------------------------

-- ADD NEW COLUMN

ALTER TABLE ZOMATO
ADD COLUMN MONTH VARCHAR(12)

UPDATE  ZOMATO
SET
MONTH = TO_CHAR(ORDER_DATE,'MON')



-- 9. Peak Ordering Day Analysis

SELECT TO_CHAR(ORDER_DATE,'DAY') AS DAY_NAME ,COUNT(*) AS NO_OF_ORDERS,SUM(PRICE) AS TOTAL_REVENUE FROM ZOMATO
GROUP BY 1 ORDER BY 3 DESC


-- 10. QUARTERLY REVENUE TREND

SELECT EXTRACT(QUARTER FROM ORDER_DATE) AS QUARTER ,SUM(PRICE) AS REVENUE FROM ZOMATO 
GROUP BY 1 
ORDER BY 1

-- 11. MONTHLY REVENUE

SELECT MONTH, COUNT(*) AS NO_OF_ORDERS,SUM(PRICE) AS REVENUE FROM ZOMATO GROUP BY 1 ORDER BY 3 DESC

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 12. HIGH RATING BUT LOW ORDERED RESTAURANT NAMES

WITH FILTERING AS (
SELECT STATE,CITY,RESTAURANT_NAME,ROUND(AVG(RATING),2) AVG_RATING, COUNT(*) AS FREQUENCY  FROM ZOMATO
GROUP BY 1 , 2, 3
HAVING AVG(RATING) > 4.3 AND COUNT(*) < 20 )


SELECT*,ROW_NUMBER() OVER(PARTITION BY CITY) AS RK FROM FILTERING  



select * from zomato

select city,count(distinct location) as location_count, count( distinct restaurant_name) as restaurant_count from zomato group by 1



































































